name: Build debian image for OrangePi Zero 3

on:
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Build debian image for OrangePi Zero 3
        run: ./build.sh
      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: debian-image
          path: ${{ github.workspace }}/orangepi-build/output/**/*.img